### PR TITLE
fix: fix type error when generating profile picture initials

### LINKED ISSUE #2745: [bug]: unable to go to profile page when registering through email
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When logging in through email, you can't go to the profile page because the `ProfilePicture` component can't be rendered.

### Steps to reproduce

1. Login in through email
2. The `ProfilePicture` won't be rendered because there is no `photoURL` and no `displayName`

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by amk-dev**
### Description

fixes HOPPSCOTCH-APP-30

fixes #2745

### CODE REVIEW

File: packages/hoppscotch-app/src/components/app/Header.vue [hunk 1]
```diff
@@ -71,8 +71,8 @@
                   theme: 'tooltip',
                 }"
                 :url="currentUser.photoURL"
-                :alt="currentUser.displayName"
-                :title="currentUser.displayName"
+                :alt="currentUser.displayName || 'Hoppscotch User'"
+                :title="currentUser.displayName || 'Hoppscotch User'"
```
Comment (AndrewBastin) [inline packages/hoppscotch-app/src/components/app/Header.vue:75]: i18n ?

File: packages/hoppscotch-app/src/components/app/Header.vue [hunk 2]
```diff
@@ -81,7 +81,7 @@
               <ProfilePicture
                 v-else
                 v-tippy="{ theme: 'tooltip' }"
-                :title="currentUser.displayName"
+                :title="currentUser.displayName || 'Hoppscotch User'"
```
Comment (AndrewBastin) [inline packages/hoppscotch-app/src/components/app/Header.vue:84]: i18n ?

File: packages/hoppscotch-app/src/pages/profile.vue [hunk 3]
```diff
@@ -37,7 +37,7 @@
               <ProfilePicture
                 v-if="currentUser.photoURL"
                 :url="currentUser.photoURL"
-                :alt="currentUser.displayName"
+                :alt="currentUser.displayName || 'Hoppscotch User'"
```
Comment (AndrewBastin) [inline packages/hoppscotch-app/src/pages/profile.vue:40]: i18n ?

File: packages/hoppscotch-app/src/components/profile/Picture.vue [hunk 4]
```diff
@@ -65,6 +71,10 @@ export default defineComponent({
   },
   methods: {
     toHex(initial: string) {
+      if (!this.isValidInitial(initial)) {
+        initial = "HS"
```
Comment (AndrewBastin) [inline packages/hoppscotch-app/src/components/profile/Picture.vue:75]: Parameter Reassign is generally frowned upon. As based on the values passed around, it can bring upon call by reference or call by value rules. Just isolate this to a different variable. Variables are basically free.

I will add an ESLint rule (`no-param-reassign`) to prevent this in the future.

File: packages/hoppscotch-app/src/components/app/Header.vue [hunk 5]
```diff
@@ -81,7 +81,7 @@
...
                 :initial="currentUser.displayName"
```
Comment (AndrewBastin) [inline packages/hoppscotch-app/src/components/app/Header.vue:85]: This fix does nothing to fix this valid Type Error TypeScript will raise here.

**Review by AndrewBastin — CHANGES_REQUESTED** [review]
not happy with this fix :(

Please do look into the given remarks.

**Comment by amk-dev** [comment]
> not happy with this fix :(
> 
> Please do look into the given remarks.

Sorry for lame first implementation. did it in a hurry. 😇

**Review by AndrewBastin — DISMISSED** [review]
lgtm :100:

**Comment by liyasthomas** [comment]
Shall we use user’s email id as fallback for displayName as discussed in #2745.

**Comment by AndrewBastin** [comment]
@liyasthomas this is out of scope for this PR.
A new PR can be raised to fix this.

**Comment by amk-dev** [comment]
#2746

raised this PR
