### PR TITLE
fix: collection request name edit issue

### LINKED ISSUE #3114: [bug]: Rename query not works
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to rename the query the name stays the same.

### Steps to reproduce

1. Create new query in collection
2. Save query with some name, eg. "my super query"
3. Duplicate this
4. Try to rename (three dots > Edit)  "my super query - Duplicate" to  "my second super query" Rename should not works

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by anwarulislam**
### Tests

**Personal workspace**

- [x] Editing and saving requests from personal workspace > collection section - **changes should be directly saved, no dirty indicator**
- [x] Editing and saving request from personal workspace > double click the tab name - **request should be dirty with unsaved changes indicator**
- [x] Editing and saving new requests from personal workspace > new request (click on the new tab +)" - **request should be dirty with unsaved changes indicator**

**Team workspace**

- [x] Editing and saving requests from team workspace > collection section - **changes should be directly saved, no dirty indicator**
- [x] Editing and saving request from team workspace > double click the tab name - **request should be dirty with unsaved changes indicator**
- [x] Editing and saving new requests from team workspace > new request (click on the new tab +)" - **request should be dirty with unsaved changes indicator**

**Behaviours**

- [x] Dirty indicator behavior on all above cases
- [x] Manual save action behavior on all above cases

### Summary
✨🐛♻️

Simplify request name editing in collections modal. Use `v-model` and `editingRequestName` ref to bind data and UI elements in `collections/index.vue`.

> _We're editing request names with ease_
> _Using `v-model` and a `ref`_
> _No more messy data flow to tease_
> _Just a modal dialog that's smooth and def_

### Walkthrough
*  Simplify data binding for editing request name in modal dialog ([link](https://github.com/hoppscotch/hoppscotch/pull/3115/files?diff=unified&w=0#diff-bea4d3e00e3d1167aa2228f3ce3d9a582dc3a006e0753c3806c6e8f1ec0d4080L129-R129), [link](https://github.com/hoppscotch/hoppscotch/pull/3115/files?diff=unified&w=0#diff-bea4d3e00e3d1167aa2228f3ce3d9a582dc3a006e0753c3806c6e8f1ec0d4080R291), [link](https://github.com/hoppscotch/hoppscotch/pull/3115/files?diff=unified&w=0#diff-bea4d3e00e3d1167aa2228f3ce3d9a582dc3a006e0753c3806c6e8f1ec0d4080R864), [link](https://github.com/hoppscotch/hoppscotch/pull/3115/files?diff=unified&w=0#diff-bea4d3e00e3d1167aa2228f3ce3d9a582dc3a006e0753c3806c6e8f1ec0d4080R882))

Closes HFE-75
Closes #3114

### CODE REVIEW

**Comment by liyasthomas** [comment]
**Multiple bugs, check the screen record below:**

<video src="https://github.com/hoppscotch/hoppscotch/assets/10395817/27c44dac-acb7-4272-a339-6284936fc9d0" />

<video src="https://github.com/hoppscotch/hoppscotch/assets/10395817/920c23bb-5ab8-4ee7-a2ca-9b60aa20b4f5" />

**Review by liyasthomas — CHANGES_REQUESTED** [review]
https://github.com/hoppscotch/hoppscotch/pull/3115#issuecomment-1576961204

**Comment by liyasthomas** [comment]
The previous errors seem to be resolved - still, there's one issue. While editing the request name of an unsaved request - it asks me to save the request. This shouldn't happen.

[ad85dfc6-7be1-4de0-8edb-cb94b084cbb1.webm](https://github.com/hoppscotch/hoppscotch/assets/10395817/dd24ad1b-ec6e-4c6e-be7c-1be82ae4703c)

**Comment by anwarulislam** [comment]
> The previous errors seem to be resolved - still, there's one issue. While editing the request name of an unsaved request - it asks me to save the request. This shouldn't happen.

I see. This is related to the request that just opened and was not saved into a collection. I'm fixing this, right away

**Review by nivedin — CHANGES_REQUESTED** [review]
while changing the personal tab req name it made the tab dirty and not while changing the team req tab.

**Comment by anwarulislam** [comment]
> while changing the personal tab req name it made the tab dirty and not while changing the team req tab.

@liyasthomas this is what we have fixed. Should we save the request by default if there is a save context or we just leave it like this for the user to save?

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

File: packages/hoppscotch-common/src/components/collections/index.vue [hunk 1]
```diff
@@ -860,6 +861,7 @@ const editRequest = (payload: {
 }) => {
   const { folderPath, requestIndex, request } = payload
   editingRequest.value = request
+  editingRequestName.value = request.name || ""
```
Comment (AndrewBastin) [inline packages/hoppscotch-common/src/components/collections/index.vue:864]: Why the OR assignment ?

`request.name` cannot be a nullish value (it is typed as a string).

**Review by AndrewBastin — CHANGES_REQUESTED** [review]

**Review by nivedin — CHANGES_REQUESTED** [review]
https://github.com/hoppscotch/hoppscotch/assets/53208152/3ce28c5f-6dd0-4d55-a2cc-fa5cc8dbac63

this [issue](https://github.com/hoppscotch/hoppscotch/pull/3115#pullrequestreview-1464696764) still exists

**Comment by anwarulislam** [comment]
@liyasthomas what we decided about this UX? are we going to make it dirty for both or not?

**Comment by liyasthomas** [comment]
@anwarulislam the UX is what we discussed. Changing the request name on from Tab should change the saved request name in the collection. But here, what @nivedin is trying to convey is that, in the case of a team collection, the request name change directly got reflected in the collection but fora personal collection, even after thou request name is updated, the request shows there are unsaved changes - this doesn't make any sense.

In personal collection > request, changing the name from tab/collection/anywhere should not make the request dirty, instead, it should save the request with its new name.

**Comment by liyasthomas** [comment]
Since the user flow of editing the request name brings up this UX flow, ideally this should be fixed within this PR.

@nivedin, I'm open to ideas.

**Comment by nivedin** [comment]
@anwarulislam I could not reproduce the issue with the team collection request not being updated in the UI. 

Our issue here is that we have to set the dirty as false after renaming the tab, which works fine for team requests only for personal requests does this issue exists.

**Review by liyasthomas — APPROVED** [review]
LGTM

**Review by nivedin — APPROVED** [review]
LGTM 💯
