### PR TITLE
fix: Cannot set custom method #3406

### LINKED ISSUE #3406: [bug]: Cannot set custom method
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to set custom request method , `[Vue warn]: Error in 1: "TypeError: e.method is undefined"` pop up in console. And I can't set custom request method.

### Steps to reproduce

1. Set custom method
   image
2. Click Send
3. Custom method disappear & not working
  image
  image

### Environment

Production

### Version

Local

### PR DESCRIPTION
**Pull request by dreygur**
Closes #3406

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

File: packages/hoppscotch-common/src/components/http/Request.vue [hunk 1]
```diff
@@ -632,6 +632,7 @@ defineActionHandler("request.show-code", () => {
 })
 
 const isCustomMethod = computed(() => {
+  console.log("Custom method", newMethod.value)
```
Comment (liyasthomas) [inline packages/hoppscotch-common/src/components/http/Request.vue:635]:
```suggestion
```

**Review by liyasthomas — DISMISSED** [review]
LGTM 💯

**Comment by anwarulislam** [comment]
I found another bug while reviewing the PR. When we set the method to `CUSTOM` and then select a method from autocomplete, an unknown `KeyboardEvent` is triggered with no `KeyCode` and the method set to undefined. I am not sure if this is only happening on my machine or not. I am using chromium (v117) on macOS.

**Review by anwarulislam — APPROVED** [review]
