### PR TITLE
fix: use pressed key rather than its code

### LINKED ISSUE #3833: [bug]: keyboard shortcuts not respecting different keyboard layout, e.g. dvorak
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using dvorak keyboard layout, so the `.` key on my keyboard is actually `v`.  
When I press CTRL and this key, hopscotch says `copied to clipboard`, while I intended to paste.  
Hopscotch obviously thinks I pressed `CTRL+.`, but that's not the case. 

### Steps to reproduce

1. Switch your keyboard layout to dvorak (I'm using windows)  
2. Open hopscotch 
3. Press CTRL and the key with `.` printed on it.  (so to an ousider, to someone who's watching you behind your shoulder, you are pressing `CTRL+.`, but what you are really pressing is `CTRL+v`)  
4. Hopscotch shows `copied to clipboard` 

### Environment

Production

### Version

Local

### PR DESCRIPTION
**Pull request by posva**
Fix #3833

Closes # 

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by posva** [comment]
BTW, I think the code can be simplified but I don't know if there is any issue with returning keys that aren't valid `key` characters:

```ts
function getPressedKey(ev: KeyboardEvent): Key {
  const key = ev.key.toLowerCase()

  if (key.startsWith("arrow")) {
    return key.slice(5) as Key
  }

  return key as Key
}
```

File: packages/hoppscotch-common/src/helpers/keybindings.ts [hunk 1]
```diff
@@ -132,30 +132,26 @@ function generateKeybindingString(ev: KeyboardEvent): ShortcutKey | null {
...
   // Check arrow keys
   if (val === "arrowup") return "up"
   else if (val === "arrowdown") return "down"
   else if (val === "arrowleft") return "left"
   else if (val === "arrowright") return "right"
 
+  const key = ev.key.toLowerCase()
+
   // Check letter keys
   const isLetter = val.startsWith("key")
```
Comment (JoelJacobStephen) [inline packages/hoppscotch-common/src/helpers/keybindings.ts:146]: Since we are using `ev.key` instead of `ev.code`, `val` string won't have key or digit in the beginning of the string ( `val` returns `a` instead of `key a`, and in case of a digit, it returns `0` instead of `digit 0`). The check right now will always return false, which results in few shortcuts not being invoked.

File: packages/hoppscotch-common/src/helpers/keybindings.ts [hunk 2]
```diff
@@ -132,30 +132,26 @@ function generateKeybindingString(ev: KeyboardEvent): ShortcutKey | null {
...
-  if (isLetter) return val.substring(3) as Key
+  if (isLetter) return key as Key
 
   // Check if number keys
   const isDigit = val.startsWith("digit")
```
Comment (JoelJacobStephen) [inline packages/hoppscotch-common/src/helpers/keybindings.ts:150]: > Since we are using `ev.key` instead of `ev.code`, `val` string won't have key or digit in the beginning of the string ( `val` returns `a` instead of `key a`, and in case of a digit, it returns `0` instead of `digit 0`). The check right now will always return false, which results in few shortcuts not being invoked.

We can  rather do a simple digit check here.

**Review by JoelJacobStephen — CHANGES_REQUESTED** [review]
@posva Please look into these comments.

File: packages/hoppscotch-common/src/helpers/keybindings.ts [hunk 3]
```diff
@@ -132,30 +132,26 @@ function generateKeybindingString(ev: KeyboardEvent): ShortcutKey | null {
 
 function getPressedKey(ev: KeyboardEvent): Key | null {
   // Sometimes the property code is not available on the KeyboardEvent object
-  const val = (ev.code ?? "").toLowerCase()
+  const val = (ev.key ?? "").toLowerCase()
```
Comment (posva) [inline packages/hoppscotch-common/src/helpers/keybindings.ts:135]:
```suggestion
  const val = (ev.code ?? "").toLowerCase()
```

File: packages/hoppscotch-common/src/helpers/keybindings.ts (hunk 1 above)
Comment (posva) [reply packages/hoppscotch-common/src/helpers/keybindings.ts:146]: yeah, I didn't mean to change the value of `val`, it was left from the refactoring I showed in the comment in the PR.

I reverted that so now it works

File: packages/hoppscotch-common/src/helpers/keybindings.ts [hunk 4]
```diff
@@ -132,30 +132,26 @@ function generateKeybindingString(ev: KeyboardEvent): ShortcutKey | null {
...
 
   // Check arrow keys
   if (val === "arrowup") return "up"
   else if (val === "arrowdown") return "down"
   else if (val === "arrowleft") return "left"
   else if (val === "arrowright") return "right"
 
+  const key = ev.key.toLowerCase()
```
[the remark this answers is not in the document]
Comment (posva) [reply packages/hoppscotch-common/src/helpers/keybindings.ts:143]: fixed

File: packages/hoppscotch-common/src/helpers/keybindings.ts (hunk 2 above)
Comment (posva) [reply packages/hoppscotch-common/src/helpers/keybindings.ts:150]: Yes, and it could be even simpler if you want: https://github.com/hoppscotch/hoppscotch/pull/3978#issuecomment-2056371408

Comment (posva) [reply packages/hoppscotch-common/src/helpers/keybindings.ts:150]: BTW feel free to push any changes to the PR

**Comment by JoelJacobStephen** [comment]
@posva I have updated the logic for the checks to work with `ev.key` 

> [#3627832](https://github.com/hoppscotch/hoppscotch/pull/3978/commits/36278320d3c00cda255ddacafba3ca332905062d). 

I have also incorporated your suggestions. Can you please verify from your end if the latest changes work as intended and resolves the [issue](https://github.com/hoppscotch/hoppscotch/issues/3833)?

**Comment by posva** [comment]
I tried building locally but it gives some errors with prisma so I gave up 😅 
Other than that, the code looks good! As long as `key` is used, it should work 👍

**Review by JoelJacobStephen — APPROVED** [review]

**Comment by AndrewBastin** [comment]
> I tried building locally but it gives some errors (even on main branch) with prisma so I gave up 😅
@posva can you confirm if you are using Windows ? We have a known annoying little type checking issue with Prisma over there.

Merging into release.

**Comment by posva** [comment]
It was on osx
