### PR TITLE
fix: sticky searchbar hidden in codemirror

### LINKED ISSUE #3240: [feature]: search bar on request response always present when scrolling
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, when trying to search for something, you press CTRL + F, and it works fine, but the problem is that the search bar stays at the top of the request response, and does not follow the scroll, so it's a bit annoying, because I can't use the search controls at the bottom of the request response.

It would be nice if even if you scroll the search bar is always visible.

https://github.com/hoppscotch/hoppscotch/assets/56084970/c81349b0-8b2e-46a0-9e80-9583ec3def1e

### Why should this be worked on?

For better UX, as there are cases where we need to look for something in what is far below the request response.

### PR DESCRIPTION
**Pull request by nivedin**
Closes #3240 
Closes HFE-211

### Description
This PR fixes the issue in code mirror instances where the search panel gets hidden when scrolling because of the sticky nature of the components above it.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

File: packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue [hunk 1]
```diff
@@ -86,7 +86,14 @@
...
       </div>
     </div>
-    <div ref="jsonResponse" class="flex flex-col flex-1 h-auto h-full"></div>
+    <div
+      ref="jsonResponse"
+      class="flex flex-col flex-1 h-auto h-full"
+      :class="{
+        responseToggleOff: !toggleFilter,
+        responseToggleOn: toggleFilter,
+      }"
```
Comment (jamesgeorge007) [inline packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue:95]:
```suggestion
      :class="toggleFilter ? 'responseToggleOn' : 'responseToggleOff'"
```

How about leveraging ternary here?

File: packages/hoppscotch-common/src/composables/codemirror.ts [hunk 2]
```diff
@@ -221,6 +221,7 @@ export function useCodemirror(
     if (selection) {
       const from = selection.from
       const to = selection.to
```
Comment (jamesgeorge007) [inline packages/hoppscotch-common/src/composables/codemirror.ts:223]:
```suggestion
      const { from, to } = selection
```
