### PR TITLE
fix: use --location param for url when parsing curl

### LINKED ISSUE #3109: Import CURL does not work
Hey, 

Trying to import a valid CURL and it does not work, it only sets the method type, and sometimes sets the headers and body, 
and the URL is set to https://echo.hoppscotch.io/

curl --location 'http://my-private-url.test.com' \
--header 'Accept: application/jsonx' \
--header 'Content-Type: application/jsonx' \
--data '{"a":1,"b":2,"c":3}'

the curl imports fine in Postman.

Can you please check and advise? thanks

### PR DESCRIPTION
**Pull request by amk-dev**
Fixes #3109 

### Url is not properly parsed when importing using curl 

**Before**

We were not respecting the `--location` parameter when parsing the curl request.

**After** 

Respect the `--location` parameter when parsing the curl request.

### Body And Headers are not loaded properly

**Before**

In component `RequestOptions.vue`, we have a ref `request` which is set to `props.modelValue` in the setup function. but when the component updates with new props, this is not updated. this caused child components that uses this `request` ref to not get updated reactively.

**After**

Added a watcher that updates the `request` ref, when the props change.

### CODE REVIEW

**Review by nivedin — CHANGES_REQUESTED** [review]
```
curl --location 'http://my-private-url.test.com/'
--header 'Accept: application/jsonx'
--header 'Content-Type: application/jsonx'
--data '{"a":1,"b":2,"c":3}'
```

when trying to import the curl the body is not set, and setting the header has also some bugs.

**Review by nivedin — APPROVED** [review]
LGTM 💯

File: packages/hoppscotch-common/src/components/http/RequestOptions.vue [hunk 1]
```diff
@@ -72,6 +72,10 @@ const emit = defineEmits<{
 
 const request = ref(props.modelValue)
 
+watch(props, (updatedProps) => {
```
Comment (AndrewBastin) [inline packages/hoppscotch-common/src/components/http/RequestOptions.vue:75]: I think we have `request` just representing the modelValue right ?
In that case, why not just define `request` using `useVModel` ?

Will something break ?
```ts
import { useVModel } from "@vueuse/core"

const request = useVModel(props, "modelValue", emit)
```

**Review by AndrewBastin — CHANGES_REQUESTED** [review]

**Review by AndrewBastin — APPROVED** [review]
lgtm
