### PR TITLE
fix: language switching issue to en from slug

### LINKED ISSUE #2959: [bug]: When I tried to change the app language  to English with router, it could not take effect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I tried to change the app language  to English with url, it could not take effect 

### Steps to reproduce

I changed the app language to chinese with url , it took effect.
image
image
when I changed the app language from chinese to english, it could not take effect.
image
image

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by anwarulislam**
Closes #2959 

### Description
This PR resolves the issue of switching to `en` locale from URL slug. Allowed dynamic import using `vite-plugin-vue-i18n` this plugin.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

File: packages/hoppscotch-common/src/modules/i18n.ts [hunk 1]
```diff
@@ -123,11 +123,6 @@ export default <HoppModule>{
       fallbackLocale: "en",
       legacy: false,
       allowComposition: true,
```
Comment (amk-dev) [inline packages/hoppscotch-common/src/modules/i18n.ts:125]: can you also remove this unused import 

`import en from "../../locales/en.json"`

**Review by amk-dev — CHANGES_REQUESTED** [review]

**Comment by anwarulislam** [comment]
It is also working after adding a little delay before switching to `en` inside onBeforeRouteChange

**Review by amk-dev — DISMISSED** [review]
LGTM 🚀
