### PR TITLE
fix: overflowing modal fix on small screens

### LINKED ISSUE #3642: [bug]: Show Code Modal Overflowing on Large Code
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I press `Show Code` for the request and choose a language which generates large code like `Go`. The modal is overflowing and the buttons `Copy` and `Dismiss` are completely inaccessible. 

### Steps to reproduce

1. Open a request tab with some URL
2. Click on `Show Code` in the send button options
3. Choose a language like `Go`
4. Observe the overflow

[Screencast from 12-12-23 12:13:02 PM IST.webm](https://github.com/hoppscotch/hoppscotch/assets/55492635/d61c0d8f-25f2-4ecf-bd4b-12acfd2f2746)

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by ajmalmohad**
Modal max height is set based on view port size instead of using hard coded value

Closes #3642 

### Description
Used `60vh` as body height of modal instead of `lg`

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information
[Screencast from 12-12-23 01:18:44 PM IST.webm](https://github.com/hoppscotch/hoppscotch/assets/55492635/6c66bb13-2ea3-4197-8929-6d18cfcb5528)

### CODE REVIEW

File: packages/hoppscotch-ui/src/components/smart/Modal.vue [hunk 1]
```diff
@@ -54,7 +54,7 @@
               </span>
             </div>
             <div
-              class="flex flex-col overflow-y-auto max-h-lg"
+              class="flex flex-col overflow-y-auto max-h-[60vh]"
```
Comment (liyasthomas) [inline packages/hoppscotch-ui/src/components/smart/Modal.vue:57]:
```suggestion
              class="flex flex-col overflow-y-auto max-h-[50vh]"
```

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

**Comment by liyasthomas** [comment]
Thanks for reporting the issue and opening the PR, I've set the max height to 50vh to better accommodate small screen devices.
