### PR TITLE
fix: selected env changed while sidebar collapsed

### LINKED ISSUE #2995: [bug]: when you close the sidebar and open it again, if you have env selected, it resets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you close the sidebar and open it again, if you have env selected, it resets:

image

### Steps to reproduce

1. Open any request
2. Select any env
3. Click on "Collapse sidebar"
4. Click on "Expand sidebar"

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by nivedin**
Closes #2995 

### Description
This PR resolves the problem where, when a user selects a team environment and toggles the sidebar, the selected environment is reset.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

File: packages/hoppscotch-common/src/newstore/localpersistence.ts [hunk 1]
```diff
@@ -210,35 +208,21 @@ function setupEnvironmentsPersistence() {
...
-    O.fromNullable(window.localStorage.getItem("selectedEnvIndex")),
-    O.map(parseInt), // If not null, parse to integer
-    O.chain(
-      O.fromPredicate(
-        Number.isInteger // Check if the number is proper int (not NaN)
-      )
-    ),
-    O.getOrElse(() => -1) // If all the above conditions pass, we are good, else set default value (-1)
+  const selectedEnvIndex = JSON.parse(
+    window.localStorage.getItem("selectedEnvIndex") || "null"
```
Comment (AndrewBastin) [inline packages/hoppscotch-common/src/newstore/localpersistence.ts:212]: Use `??` instead of `||` when applicable

**Review by AndrewBastin — CHANGES_REQUESTED** [review]

File: packages/hoppscotch-common/src/newstore/localpersistence.ts [hunk 2]
```diff
@@ -210,35 +208,21 @@ function setupEnvironmentsPersistence() {
 }
 
 function setupSelectedEnvPersistence() {
```
Comment (amk-dev) [inline packages/hoppscotch-common/src/newstore/localpersistence.ts:210]: when dealing with localstorage values, backward compatibility is important because different versions of the app may have different values.

in this case our old app can have selectedEnvIndex as -1, which is not a valid `selectedEnvIndex` in our new implementation. so we need to check for that handle it properly. otherwise our app can break.

there is a function `checkAndMigrateOldSettings`, where you can add the check. 

```suggestion
const selectedEnvIndex = localStorage.getItem("selectedEnvIndex")

  if (selectedEnvIndex == "-1") {
    localStorage.setItem(
      "selectedEnvIndex",
      JSON.stringify({
        type: "NO_ENV_SELECTED",
      })
    )
  }
```

File: packages/hoppscotch-common/src/components/environments/index.vue [hunk 3]
```diff
@@ -408,7 +408,6 @@ const selectedEnv = computed(() => {
         teamEnvID: selectedEnvironmentIndex.value.teamEnvID,
       }
     } else {
-      selectedEnvironmentIndex.value = { type: "NO_ENV_SELECTED" }
       return { type: "NO_ENV_SELECTED" }
     }
   } else {
```
Comment (amk-dev) [inline packages/hoppscotch-common/src/components/environments/index.vue:413]: It is a bad practice to have side effects in computed properties. since we're here already,     can you also remove the `selectedEnvironmentIndex.value = { type: "NO_ENV_SELECTED" }` from the next else, if it doesnt serve any purpose. if it has purpose, we can move it to a watcher

**Review by amk-dev — CHANGES_REQUESTED** [review]
look into the comments

**Review by amk-dev — APPROVED** [review]
LGTM 🚀

**Review by AndrewBastin — APPROVED** [review]
