### PR TITLE
fix: fix issue for multipart/form-data and cookie header (#4162)

### LINKED ISSUE #4162: [bug]: pc app not network when choose mulitpart/form-data
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

image
### Steps to reproduce

it work when clean contentType, my controller is 
  @PostMapping("/import")
   public Response importFile(MultipartFile file, Long mId) {
       return fileService.importFile(file, mId);
    }

### Environment

Production

### Version

Local

### PR DESCRIPTION
**Pull request by shipko**
Closes #4162 

### What's changed
This PR is fixing some issues on sending file data:

1. Fix data variable type that sending to interceptor.rs 
2. Fix parameter filter for unsetted file
3. Add mime type for sending file
4. Fix double Content-Type header
5. Fix Cookie header. Removing it if not present 

### Notes to reviewers

This PR is tested on web and desktop app. Not for CLI

### CODE REVIEW

File: packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts [hunk 1]
```diff
@@ -129,7 +130,8 @@ async function processBody(axiosReq: AxiosRequestConfig): Promise<BodyDef | null
           value: {
             File: {
               filename: value.name,
-              data: new Uint8Array(await value.arrayBuffer())
+              data: Array.from(new Uint8Array(await value.arrayBuffer())),
+              mime: value.type,
```
Comment (AndrewBastin) [inline packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts:134]: If the browser/system doesn't know the Mime Type, `value.type` can be an empty string so we should avoid putting in the mime type in that situation.
See: https://arc.net/l/quote/thjiuzih

**Review by AndrewBastin — CHANGES_REQUESTED** [review]

File: packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts (hunk 1 above)
Comment (shipko) [reply packages/hoppscotch-selfhost-desktop/src/platform/interceptors/native/index.ts]: Yes, you're right!
By [rfc2046](https://www.ietf.org/rfc/rfc2046.txt) if mime type is not recognizable you should use `"application/octet-stream"` content type

**Comment by shipko** [comment]
@AndrewBastin please, review it

**Review by AndrewBastin — APPROVED** [review]
